<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>text.log</string>

		<key>fileTypes</key>
		<array>
			<string>log</string>
		</array>

		<key>name</key>
		<string>GenXs log file</string>

		<key>patterns</key>
		<array>
			<!-- GenXs Log lines -->
			<dict>
				<key>match</key>
				<string>^((\d{2}:\d{2}:\d{2}\.\d{6})(~\d+) (\d+)(#[0-9a-f]+)(?: |([|]))(?:(FATAL|ERROR)|(WARNG)|([A-Za-z]{5}))(::)((?:[^:]|:\\)+\\)?([^:]+):(\d+) +([^{ &]+)(?:({)([^}]+)(}))?(&)? ? \t)</string>

				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>genxs.log.lineprefix</string>
					</dict>
					
					<key>2</key>
					<dict>
						<key>name</key>
						<string>comment.block genxs.log.time</string>
					</dict>
					
					<key>3</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.integer.decimal genxs.log.thread</string>
					</dict>
					
					<key>4</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.integer.decimal genxs.log.ticks</string>
					</dict>
					
					<key>5</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.integer.hexadecimal genxs.log.hash</string>
					</dict>
					
					<key>6</key>
					<dict>
						<key>name</key>
						<string>token.warn-token strong genxs.log.muted</string>
					</dict>
					
					<key>7</key>
					<dict>
						<key>name</key>
						<string>token.error-token log.error genxs.log.level.error</string>
					</dict>
					
					<key>8</key>
					<dict>
						<key>name</key>
						<string>token.warn-token log.warning genxs.log.level.warning</string>
					</dict>
					
					<key>9</key>
					<dict>
						<key>name</key>
						<string>token.info-token log.info genxs.log.level</string>
					</dict>
					
					<key>10</key>
					<dict>
						<key>name</key>
						<string>punctuation.separator genxs.log.separator</string>
					</dict>
					
					<key>11</key>
					<dict>
						<key>name</key>
						<string>entity.name.namespace genxs.log.path</string>
					</dict>
					
					<key>12</key>
					<dict>
						<key>name</key>
						<string>entity.name.class genxs.log.file</string>
					</dict>
					
					<key>13</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.integer.decimal genxs.log.linenumber</string>
					</dict>
					
					<key>14</key>
					<dict>
						<key>name</key>
						<string>entity.name.function genxs.log.method</string>
					</dict>
					
					<key>15</key>
					<dict>
						<key>name</key>
						<string>comment.block punctuation.definition.comment genxs.log.separator</string>
					</dict>
					
					<key>16</key>
					<dict>
						<key>name</key>
						<string>constant genxs.log.context</string>
					</dict>
					
					<key>17</key>
					<dict>
						<key>name</key>
						<string>comment.block punctuation.definition.comment genxs.log.separator</string>
					</dict>
					
					<key>18</key>
					<dict>
						<key>name</key>
						<string>token.warn-token genxs.log.reference</string>
					</dict>
				</dict>
			</dict>

			<!-- numbers, true, false, null, #hex, GUIDs, MAC, IPv6 addresses: 89:A1:23:45:AB:C0, fde8:e767:269c:0:9425:3477:7c8f:7f1a -->
			<dict>
				<key>match</key>
				<string>\b(?:\d+(?:[,.:-]\d+(?:[^\s]+)?)*|true|false|null|#\h+|(?:\h{2,}[:-])+\h{2,}+)\b</string>

				<key>name</key>
				<string>constant genxs.log.literal</string>
			</dict>

			<!-- ISO dates ("2016-08-23") -->
			<dict>
				<key>match</key>
				<string>\b\d{4}-\d{2}-\d{2}(?=T|\b)</string>

				<key>name</key>
				<string>comment genxs.log.date</string>
			</dict>

			<!-- Culture specific dates ("23/08/2016", "23.08.2016") -->
			<dict>
				<key>match</key>
				<string>\b\d{2}[^\w\s]\d{2}[^\w\s]\d{4}\b</string>

				<key>name</key>
				<string>comment genxs.log.date.other</string>
			</dict>

			<!-- Clock times with optional timezone and optional T prefix ("T09:13:16", "09:13:16", "09:13:16.323", "09:13:16+01:00") -->
			<dict>
				<key>match</key>
				<string>\d{1,2}:\d{2}(?::\d{2}(?:[.,]\d{1,})?)?(?:Z| ?[+-]\d{1,2}:\d{2})?\b</string>
				
				<key>name</key>
				<string>comment log.date</string>
			</dict>

			<!-- Clock times without separator and with optional timezone ("T091316", "T091316.323", "T091316+0100") -->
			<dict>
				<key>match</key>
				<string>T\d{2}\d{2}(\d{2}([.,]\d{1,})?)?(Z| ?[+-]\d{1,2}\d{2})?\b</string>

				<key>name</key>
				<string>comment genxs.log.time.other</string>
			</dict>

			<!-- Git commit hashes of length 7, 10 or 40 -->
			<dict>
				<key>match</key>
				<string>\b(?:\h{7}(\h{3}|\h{33})?)\b</string>

				<key>name</key>
				<string>constant.numeric.integer.hexadecimal genxs.log.githash</string>
			</dict>

			<!-- Hex Constants -->
			<dict>
				<key>match</key>
				<string>\b(0x[a-fA-F0-9]+)\b</string>

				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>

			<!-- String constants -->
			<dict>
				<key>match</key>
				<string>"[^"]*"</string>

				<key>name</key>
				<string>string.quoted.double</string>
			</dict>

			<dict>
				<key>match</key>
				<string>(?<![\w])'[^']*'</string>

				<key>name</key>
				<string>string</string>
			</dict>

			<!-- Exception type names -->
			<dict>
				<key>match</key>
				<string>\b(?:[a-zA-Z.]*Exception)\b</string>

				<key>name</key>
				<string>string.regexp emphasis genxs.log.exception</string>
			</dict>

			<!-- Colorize rows of exception call stacks -->
			<dict>
				<key>begin</key>
				<string>^[\t ]*at[\t ]</string>

				<key>end</key>
				<string>$</string>

				<key>name</key>
				<string>string.key emphasis genxs.log.stacktrace</string>
			</dict>

			<!-- Match Urls -->
			<dict>
				<key>match</key>
				<string>\b[a-z]+://\S+\b/?</string>

				<key>name</key>
				<string>constant.language</string>
			</dict>

			<!-- Match character and . sequences (such as namespaces)
			as well as file names and extensions (e.g. bar.txt) -->
			<dict>
				<key>match</key>
				<string>(?<![\w/\\])([\w-]+\.)+([\w-])+(?![\w/\\])</string>

				<key>name</key>
				<string>constant.language</string>
			</dict>
		</array>

		<key>uuid</key>
		<string>E81BB6AB-CAC7-4C27-9A79-4137A4693EBD</string>
	</dict>
</plist>
